MVC1/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC1.Models;
using System.Data.Entity;
using System.Data.SqlClient;

namespace MVC1.Controllers
{
    public class VehiculoController : Controller
    {

        Contexto db = new Contexto();

        public class VehiculoTotal
        {
            public string Nom_marca { get; set; }
            public string Nom_serie { get; set; }
            public string Matricula { get; set; }
            public string Color { get; set; }
        }

        // GET: Vehiculo
        public ActionResult Index()
        {
            ViewBag.SerieID = new SelectList(db.Series, "ID", "Nom_serie");
            ViewBag.ExtraList = new MultiSelectList(db.Extras, "ID", "Tipo_extra");
            return View();
        }

        public ActionResult Listado()
        {
            ViewBag.nomMarca = db.Marcas.ToList();
            ViewBag.tipoExtra = db.Extras.ToList();
            var vehiculos = db.Vehiculos.Include(a => a.Serie).Include(v => v.VehiculoExtras);
            return View(vehiculos.ToList());
        }

        public ActionResult ListadoSelectivo(int MarcaId = 1, int SerieId = 0)
        {
            ViewBag.MarcaId = new SelectList(db.Marcas, "ID", "Nom_marca");
            ViewBag.SerieId = new SelectList(db.Series.Where(s => s.MarcaID == MarcaId).OrderBy(s => s.Nom_serie), "ID", "Nom_serie");
            var vehiculos = db.Vehiculos.Where(v => v.SerieID == SerieId).ToList();

            return View(vehiculos);
        }

        public ActionResult Listado2()
        {
            db.Database.SqlQuery<VehiculoTotal>("getSeriesVehiculos").ToList();
            return View();
        }

        public ActionResult ListadoPorColor(string color="")
        {
            ViewBag.color = new SelectList(db.Vehiculos.Select(v => new { Color = v.Color }).Distinct(), "Color", "Color");
            var lista = db.Database.SqlQuery<VehiculoTotal>("getVehiculosPorColor @ColorSel", new SqlParameter("@ColorSel", color)).ToList();
            return View(lista);
        }

        public ActionResult Busqueda(string busca="")
        {
            var lista = (from p in db.Vehiculos.Include(a => a.Serie) where p.Matricula.Contains(busca) select p).ToList();
            return View(lista);
        }

        public ActionResult Busqueda2(string Matricula = "")
        {
            ViewBag.Matricula = new SelectList(db.Vehiculos, "Matricula", "Matricula");
            var lista = (from p in db.Vehiculos.Include(a => a.Serie) where p.Matricula==Matricula select p).ToList();
            return View(lista);
        }

        // GET: Vehiculo/Details/5
        public ActionResult Details(int id)
        {
            var vehiculo = db.Vehiculos.Include(b => b.Serie).FirstOrDefault(c => c.ID == id);
            return View(vehiculo);
        }

        // GET: Vehiculo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vehiculo/Create
        [HttpPost]
        public ActionResult Create(VehiculoModelo vehiculo)
        {
            try
            {
                using (var bd = new Contexto())
                {
                    bd.Vehiculos.Add(vehiculo);
                    foreach(int extra in vehiculo.ExtrasSeleccionados)
                    {
                        var obj = new VehiculoExtrasModelo() { extraID = extra, vehiculoID = vehiculo.ID };
                        bd.VehiculosExtras.Add(obj);
                    }

                    bd.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vehiculo/Edit/5
        public ActionResult Edit(int id)
        {
            var vehiculo = db.Vehiculos.Find(id);
            ViewBag.SerieID = new SelectList(db.Series, "ID", "Nom_serie", vehiculo.SerieID);
            vehiculo.ExtrasSeleccionados = db.VehiculosExtras.Where(ve => ve.vehiculoID == id).Select(ve => ve.extraID).ToList();
            ViewBag.ExtraList = new MultiSelectList(db.Extras, "ID", "Tipo_extra", vehiculo.ExtrasSeleccionados);

            return View(vehiculo);
        }

        // POST: Vehiculo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, VehiculoModelo coche)
        {
            try
            {
                VehiculoModelo vehiculo = db.Vehiculos.SingleOrDefault(v => v.ID == id);
                vehiculo.Matricula = coche.Matricula;
                vehiculo.Color = coche.Color;
                vehiculo.SerieID = coche.SerieID;

                var extrasAEliminar = db.VehiculosExtras.Where(ve => ve.vehiculoID == coche.ID);
                foreach(VehiculoExtrasModelo extraAEliminar in extrasAEliminar)
                {
                    db.VehiculosExtras.Remove(extraAEliminar);
                }

                foreach (int extra in coche.ExtrasSeleccionados)
                {
                    var obj = new VehiculoExtrasModelo() { extraID = extra, vehiculoID = vehiculo.ID };
                    db.VehiculosExtras.Add(obj);
                }

                db.SaveChanges();
                return RedirectToAction("Listado");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vehiculo/Delete/5
        public ActionResult Delete(int id)
        {
            var vehiculo = db.Vehiculos.Include(b => b.Serie).FirstOrDefault(c => c.ID == id);
            return View(vehiculo);
        }

        // POST: Vehiculo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var vehiculo = db.Vehiculos.Find(id);
                db.Vehiculos.Remove(vehiculo);
                db.SaveChanges();
                return RedirectToAction("Listado");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC1/Views/Vehiculo/Busqueda.cshtml
@model IEnumerable<MVC1.Models.VehiculoModelo>

@{
    ViewBag.Title = "Busqueda";
}

<h2>Busqueda</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form method="get">
    <input type="search" name="busca" placeholder="Busca parte de la matrícula"/>
    <input type="submit" value="Busca!"/>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Serie.Nom_serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Nom_serie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MVC1/Views/Vehiculo/Busqueda2.cshtml
@model IEnumerable<MVC1.Models.VehiculoModelo>

@{
    ViewBag.Title = "Busqueda2";
}

<h2>Busqueda2</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form method="get">
    @Html.DropDownList("Matricula", "Selecciona una matrícula")
    <input type="submit" value="Busca!" />
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Serie.Nom_serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Nom_serie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MVC1/Views/Vehiculo/Delete.cshtml
@model MVC1.Models.VehiculoModelo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VehiculoModelo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Serie.Nom_serie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie.Nom_serie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC1/Views/Vehiculo/Details.cshtml
@model MVC1.Models.VehiculoModelo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VehiculoModelo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Serie.Nom_serie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie.Nom_serie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC1/Views/Vehiculo/Edit.cshtml
@model MVC1.Models.VehiculoModelo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Vehiculo", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehiculoModelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerieID, "SerieID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SerieID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SerieID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExtrasSeleccionados, "ExtrasSeleccionados", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.ExtrasSeleccionados, new MultiSelectList(ViewBag.ExtraList, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExtrasSeleccionados, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC1/Views/Vehiculo/Index.cshtml
@model MVC1.Models.VehiculoModelo

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Create", "Vehiculo", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VehiculoModelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerieID, "SerieID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SerieID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SerieID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExtrasSeleccionados, "ExtrasSeleccionados", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.ExtrasSeleccionados, new MultiSelectList(ViewBag.ExtraList, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ExtrasSeleccionados, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC1/Views/Vehiculo/Listado.cshtml
@model IEnumerable<MVC1.Models.VehiculoModelo>

@{
    ViewBag.Title = "Listado";
}

<h2>Listado</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Serie.Marca.Nom_marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Serie.Nom_serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehiculoExtras)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Marca.Nom_marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Nom_serie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            <table>
                @foreach (var extra in item.VehiculoExtras)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => extra.Extra.Tipo_extra)
                        </td>
                    </tr>
                }
            </table>
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MVC1/Views/Vehiculo/Listado2.cshtml
@model IEnumerable<MVC1.Controllers.VehiculoController.VehiculoTotal>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Serie.Nom_serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Nom_serie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MVC1/Views/Vehiculo/ListadoPorColor.cshtml
@model IEnumerable<MVC1.Controllers.VehiculoController.VehiculoTotal>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form method="get">
    @Html.DropDownList("color", "Selecciona un color")
    <input type="submit" value="Buscar!"/>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom_marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nom_serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nom_marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nom_serie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>

    </tr>
}

</table>

MVC1/Views/Vehiculo/ListadoSelectivo.cshtml
@model IEnumerable<MVC1.Models.VehiculoModelo>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form method="get">
    <table>
        <tr>
            <td>@Html.DropDownList("MarcaId", null, htmlAttributes: new { @class = "form-control", onchange = "this.form.submit()" })</td>
            <td>@Html.DropDownList("SerieId", null, htmlAttributes: new { @class = "form-control", onchange = "this.form.submit()" })</td>
        </tr>
    </table>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Serie.Nom_serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Nom_serie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>