MVC1/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC1.Models;

namespace MVC1.Controllers
{
    public class MarcaController : Controller
    {
        Contexto db = new Contexto();
        // GET: Marca
        public ActionResult Index()
        {        
            return View();
        }

        public ActionResult Listado()
        {
            var marcas =  db.Marcas.ToList();

            return View(marcas);
        }

        public ActionResult ListadoSeries(int id)
        {
            MarcaModelo marca = db.Marcas.Include("Series").Single(m => m.ID == id);
            return View(marca);
        }


        public ActionResult Desplegable()
        {
            Contexto db = new Contexto();
            ViewBag.Marcas = new SelectList(db.Marcas, "ID", "Nom_marca");
            ViewBag.Marcas2 = db.Marcas.ToList();
            return View();
        }

        // GET: Marca/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Marca/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Marca/Create
        [HttpPost]
        public ActionResult Create(MarcaModelo marca)
        {
            try
            {
               using(var bd = new Contexto())
                {
                    bd.Marcas.Add(marca);
                    bd.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Marca/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Marca/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Marca/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Marca/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC1/Views/Marca/Desplegable.cshtml
@using MVC1.Models;
@{
    ViewBag.Title = "Desplegable";
}

<h2>Desplegable</h2>

@Html.DropDownList("LasMarcas", new List<SelectListItem>
{
    new SelectListItem { Text = "Opel", Value = "1", Selected = true},
    new SelectListItem { Text = "Renault", Value = "2"},
    new SelectListItem { Text = "Alfa Romeo", Value = "3"}
}, "Selecciona Marca")

@Html.DropDownList("Marcas", "Selecciona Marca")

<select id="Marcos" name="Marcos">
    @foreach(MarcaModelo m in ViewBag.Marcas2)
    {
        <option value="@m.ID">@m.Nom_marca</option>
    }
</select>

MVC1/Views/Marca/Index.cshtml
@model MVC1.Models.MarcaModelo

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("Create", "Marca", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MarcaModelo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom_marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom_marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom_marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC1/Views/Marca/Listado.cshtml
@model IEnumerable<MVC1.Models.MarcaModelo>

@{
    ViewBag.Title = "Listado";
}

<h2>Listado</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom_marca)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Nom_marca, "ListadoSeries", new { id = item.ID }) 
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MVC1/Views/Marca/ListadoSeries.cshtml
@model MVC1.Models.MarcaModelo

@{
    ViewBag.Title = "ListadoSeries";
}

<h2>ListadoSeries</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<h2 align="center">@Html.DisplayName(Model.Nom_marca)</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Series")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Series) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nom_serie)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>